In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [3]:
df = pd.read_csv("../data/nifty50_daily.csv")
df.head()

,Date,Open,High,Low,Close,Shares Traded,Turnover (₹ Cr)
0,2015-11-09,7788.25,7937.75,7771.70,7915.20,218422388.0,9376.17
1,2015-11-10,7877.60,7885.10,7772.85,7783.35,170267413.0,7153.47
2,2015-11-11,7838.80,7847.95,7819.10,7825.00,22380435.0,1123.44
3,2015-11-13,7762.45,7775.10,7730.90,7762.25,165876819.0,7731.55
4,2015-11-16,7732.95,7838.85,7714.15,7806.60,154134885.0,6871.15

In [4]:
df["Date"] = pd.to_datetime(df["Date"])
df = df.sort_values("Date").reset_index(drop=True)

df.tail()

,Date,Open,High,Low,Close,Shares Traded,Turnover (₹ Cr)
2143,2024-07-08,24329.45,24344.60,24240.55,24320.55,266299131.0,26356.03
2144,2024-07-09,24351.00,24443.60,24331.90,24433.20,250537091.0,29361.08
2145,2024-07-10,24459.85,24461.05,24141.80,24324.45,292263786.0,35358.54
2146,2024-07-11,24396.55,24402.65,24193.75,24315.95,306404194.0,32115.44
2147,2024-07-12,24387.95,24592.20,24331.15,24502.15,325823474.0,39565.33

In [5]:
features = [
    "Open",
    "High",
    "Low",
    "Close",
    "Shares Traded",
    "Turnover (₹ Cr)"
]

target = "Close"

X = df[features]
y = df[target]

In [6]:
train_end = "2021-12-31"
val_end = "2023-12-31"

X_train = X[df["Date"] <= train_end]
y_train = y[df["Date"] <= train_end]

X_val = X[(df["Date"] > train_end) & (df["Date"] <= val_end)]
y_val = y[(df["Date"] > train_end) & (df["Date"] <= val_end)]

X_test = X[df["Date"] > val_end]
y_test = y[df["Date"] > val_end]

len(X_train), len(X_val), len(X_test)

(1521, 494, 133)

In [7]:
# Shift close price by 1 day
y_pred_naive = y_test.shift(1)

# Drop first NaN
y_test_aligned = y_test.iloc[1:]
y_pred_naive = y_pred_naive.iloc[1:]

In [10]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

rmse_naive = np.sqrt(mean_squared_error(y_test_aligned, y_pred_naive))
mae_naive = mean_absolute_error(y_test_aligned, y_pred_naive)

rmse_naive, mae_naive

(np.float64(212.73026788635434), 136.2155303030305)